CREATE TABLE gpu_container_digests (
    id                     BIGSERIAL,
    interval_start         TIMESTAMP NOT NULL,
    cluster_uuid           UUID NOT NULL,
    namespace              TEXT NOT NULL,
    workload               TEXT NOT NULL,
    workload_type          TEXT NOT NULL DEFAULT 'deployment',
    container_name         TEXT NOT NULL,
    gpu_model_name         TEXT NOT NULL,
    gpu_profile_name       TEXT,
    fb_usage_min_mib       REAL,
    fb_usage_max_mib       REAL,
    fb_usage_avg_mib       REAL,
    tensor_pipe_active_min REAL,
    tensor_pipe_active_max REAL,
    tensor_pipe_active_avg REAL,
    dram_active_min        REAL,
    dram_active_max        REAL,
    dram_active_avg        REAL,
    sm_active_min          REAL,
    sm_active_max          REAL,
    sm_active_avg          REAL,
    PRIMARY KEY (id, interval_start)
) PARTITION BY RANGE (interval_start);
